dist: trusty
sudo: required
language: node_js
node_js:
- "6"
os:
- linux
env:
  - TEST_DIR=dawn
  - TEST_DIR=runtime
before_install:
- mkdir -p artifacts
- if [[ $TEST_DIR = dawn ]] && git tag -l --points-at HEAD | grep dawn; then
    export DEPLOY_ARTIFACTS=1;
  fi
- if [[ $TEST_DIR = runtime ]] && git tag -l --points-at HEAD | grep runtime; then
    export DEPLOY_ARTIFACTS=1;
  fi
- mkdir -p build-deps
- export PATH="$PATH:$PWD/build-deps/bin"
install:
- pushd $TEST_DIR
- make install
- if [[ $DEPLOY_ARTIFACTS = 1 ]]; then
    make artifacts-install;
  fi
- popd
script:
- pushd $TEST_DIR
- make test
- make lint
- if [[ $DEPLOY_ARTIFACTS = 1 ]]; then
    make artifacts;
  fi
- popd
branches:
  only:
  - master
  - /^(dawn)\/.*$/
  - /^(runtime)\/.*$/
  - /^(test)\/.*$/
deploy:
  provider: releases
  api_key:
    secure: n8qRthwWcGG2QqPR0r6a/50XEktDYYYKRT5X8Xr1tUYKBRoSYVYUCmGYdtUg4R0fDa5DzaDIKT0jiu4XB5S0TAUhyZNTogNcCE8sSRSWWBL3pBW6X+xa2OQfH1mABLHoqH8TGIAQ/PPRtOR8RYrpVE5vttPMIVoH/+FUyq+LAUbEbJ110qCAXie6xAHmfk6VqG4bINeDC//Kv9jnwKqR9OqSA6hn+DasevxpQENBWC6xTsLfX5f0Qy5SpOD6NalZ40QPZh1GMHWoZFoebzjCIzOcyBhDCcvta/L6PliMK6JfKINWbUPsH1knbh4S51y1UnUUXiZxc58RvjLW2THOZdYq96J3fJc7v+IY7w07AttcDIy2N1vi7H9gnlRgLpVJ5JB0pUjgpOSi1pxWOPo/hgK0MUOYPi4SVK095oPVQszMXDB3fGmB7Bo2j1uyACBad7C/8HN2m7lBjKw+82Y6k7x8bNZc0cX8J2jp6YSCtzI2LELyHxahVg8OxjAp14zBDdAJ4XsABrzeuVmPO0Xyc+OkqgYCUpF2+rJFNzgPGylBMmZix9xy+DEq0EU2benx6XbtkZ9AqX7YfQ69hhV0RVrAdpLGDv/wZYAdXvsGTOsO9EkGBv9Drn30cOolah1uHetPYAbLYpDeMeoqZQLZJP78jAXXk/wnehQlijmehEg=
  file: artifacts/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    condition: $DEPLOY_ARTIFACTS = 1
